#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

DOKKU_JMONIT_DOCKERCOMPOSE="docker/compose:1.23.2"
DOKKU_JMONIT_PLUGIN_PATH="/var/lib/dokku/plugins/enabled/jmonit"

f_dokku_jmonit_ps() {
  (cd $DOKKU_JMONIT_PLUGIN_PATH; ./docker-compose ps)
}

f_dokku_jmonit_start() {
  (cd $DOKKU_JMONIT_PLUGIN_PATH; ./docker-compose up -d)
}

f_dokku_jmonit_stop() {
  (cd $DOKKU_JMONIT_PLUGIN_PATH; ./docker-compose down)
}

f_dokku_jmonit_rm() {
  (cd $DOKKU_JMONIT_PLUGIN_PATH; ./docker-compose rm)
}

f_dokku_jmonit_kill() {
  (cd $DOKKU_JMONIT_PLUGIN_PATH; ./docker-compose kill)
}

f_dokku_jmonit_logs() {
  (cd $DOKKU_JMONIT_PLUGIN_PATH; ./docker-compose logs)
}

f_dokku_jmonit_install() {
  f_dokku_jmonit_stop
  f_dokku_jmonit_rm
  f_dokku_jmonit_start
}

f_dokku_jmonit_uninstall() {
  f_dokku_jmonit_stop
  f_dokku_jmonit_rm
}

case "$1" in
  #jmonit)
  #  f_dokku_jmonit_ps;;

  jmonit:ps)
    f_dokku_jmonit_ps;;

  jmonit:start)
    f_dokku_jmonit_start;;

  jmonit:stop)
    f_dokku_jmonit_stop;;

  jmonit:kill)
    f_dokku_jmonit_kill;;

  jmonit:logs)
    f_dokku_jmonit_logs;;

  jmonit:install)
    f_dokku_jmonit_install;;

  jmonit:uninstall)
    f_dokku_jmonit_uninstall;;

  jmonit | jmonit:help)
    cat<<EOF
    jmonit, Show the status of jmonit containrs.
    jmonit:logs, See logs for all jmonit running containers.
    jmonit:ps, Show the status of jmonit containers.
    jmonit:start, Start all required jmonit containers.
    jmonit:stop, Stop all jmonit containers.
EOF
    ;;

  help)
    cat<<EOF
    jmonit
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac

