#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

DOKKU_MONIT_DOCKERCOMPOSE="docker/compose:1.23.2"

f_dokku_jmonit_ps() {
  docker run \
    -v $(pwd)/docker-compose.yml:/docker-compose.yml \
    -v $(pwd)/.env:/.env \
    -v $(pwd)/config:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOKKU_MONIT_DOCKERCOMPOSE ps
}

f_dokku_jmonit_start() {
  docker run \
    -v $(pwd)/docker-compose.yml:/docker-compose.yml \
    -v $(pwd)/.env:/.env \
    -v $(pwd)/config:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOKKU_MONIT_DOCKERCOMPOSE up -d
}

f_dokku_jmonit_stop() {
  docker run \
    -v $(pwd)/docker-compose.yml:/docker-compose.yml \
    -v $(pwd)/.env:/.env \
    -v $(pwd)/config:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOKKU_MONIT_DOCKERCOMPOSE down
}

f_dokku_jmonit_kill() {
  docker run \
    -v $(pwd)/docker-compose.yml:/docker-compose.yml \
    -v $(pwd)/.env:/.env \
    -v $(pwd)/config:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOKKU_MONIT_DOCKERCOMPOSE kill
}

f_dokku_jmonit_logs() {
  docker run \
    -v $(pwd)/docker-compose.yml:/docker-compose.yml \
    -v $(pwd)/.env:/.env \
    -v $(pwd)/config:/config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    $DOKKU_MONIT_DOCKERCOMPOSE logs
}

f_dokku_jmonit_install() {
  f_dokku_jmonit_start
}

case "$1" in
  jmonit)
    f_dokku_jmonit_ps;;

  jmonit:ps)
    f_dokku_jmonit_ps;;

  jmonit:start)
    f_dokku_jmonit_start;;

  jmonit:stop)
    f_dokku_jmonit_stop;;

  jmonit:kill)
    f_dokku_jmonit_kill;;

  jmonit:start)
    f_dokku_jmonit_logs;;

  jmonit:install)
    f_dokku_jmonit_install ;;

  help | jmonit:help)
    cat<<EOF
    jmonit, Show the status of jmonit containrs.
    jmonit:logs, See logs for all jmonit running containers.
    jmonit:ps, Show the status of jmonit containers.
    jmonit:start, Start all required jmonit containers.
    jmonit:stop, Stop all jmonit containers.
EOF
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac

